name: Build Binary
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      name:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        id: pysetup
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt

      - name: Build Binary (Linux/Mac)
        if: runner.os != 'Windows'
        run: |
          pyinstaller core.spec \
            --clean \
            --noconfirm \
            --distpath ./dist/output/${{ inputs.name }}
      - name: Build Binary (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller core.spec `
            --clean `
            --noconfirm `
            --distpath ./dist/output/${{ inputs.name }}

      - name: Flatten Directory Structure (Linux/Mac)
        if: runner.os != 'Windows'
        run: |
          cd dist/output/${{ inputs.name }}/core
          internal_dir=$(find . -maxdepth 1 -type d -name "*_internal" -print -quit)
          if [ ! -z "$internal_dir" ]; then
            mv "$internal_dir"/* .
            rm -r "$internal_dir"
          fi
      - name: Flatten Directory Structure (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd dist/output/${{ inputs.name }}/core
          $internal_dir = Get-ChildItem -Directory -Filter "_internal" | Select-Object -First 1
          if ($internal_dir) {
            Move-Item -Path "$($internal_dir.FullName)\*" -Destination .
            Remove-Item -Path $internal_dir.FullName -Recurse
          }

      - name: Archive Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: dist/output/${{ inputs.name }}/
      - name: Test Binary help command
        run: |
          cd dist/output/${{ inputs.name }}
          if [ "${{ runner.os }}" = "Windows" ]; then
            if ./core.exe --help; then echo "test passed"; else echo "test failed"; exit 1; fi
          else
            chmod +x core
            if ./core --help; then echo "test passed"; else echo "test failed"; exit 1; fi
          fi
        shell: bash
      - name: Test Binary test-validate command
        run: |
          cd dist/output/${{ inputs.name }}
          if [ "${{ runner.os }}" = "Windows" ]; then
            ./core.exe test-validate
          else
            chmod +x core
            chmod -R 755 .
            chmod -R +r resources/
            ./core test-validate
          fi
        shell: bash
      - name: Test pyreadstat
        run: |
          cd dist/output/${{ inputs.name }}
          if [ "${{ runner.os }}" = "Windows" ]; then
            if ./core.exe test-pyreadstat; then echo "test passed"; else echo "test failed"; exit 1; fi
          else
            chmod +x core
            if ./core test-pyreadstat; then echo "test passed"; else echo "test failed"; exit 1; fi
          fi
        shell: bash
