name: Prerelease - Increment Version

on:
  workflow_dispatch:
    inputs:
      version_str:
        description: "Choose the version increment type"
        type: choice
        required: true
        default: PATCH
        options:
          - PATCH
          - MINOR
          - MAJOR

jobs:
  update_version:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Run Update Version Script
        run: echo "VERSION_OUTPUT=$(python update_version.py ${{ github.event.inputs.version_str }})" >> $GITHUB_ENV

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update version.py: ${{ env.VERSION_OUTPUT }}"
